---
name: 'C++ test'

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  images:
    name: images
    runs-on: ubuntu-latest
    permissions:
      packages: write

    strategy:
      matrix:
        include:
          - name: base-clang-libcpp
            version: 2026-02-07
          - name: base-gcc
            version: 9d9663ea153

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/${{ matrix.name }}/devcontainer.json
          imageName: ghcr.io/johnmcfarlane/simple-cpp/${{ matrix.name }}
          imageTag: ${{ matrix.version }}
          runCmd: |
            which conan
            conan --version

  unit-tests:
    name: test
    needs: [images]
    runs-on: ubuntu-latest
    permissions:
      packages: write

    strategy:
      matrix:
        include:
          - name: clang-libcpp-debug
          - name: clang-libcpp-release
          - name: clang-libcpp-test
          - name: clang-libcpp-test-tsan
          - name: clang-libcpp-analyze
          - name: gcc-debug
          - name: gcc-release
          - name: gcc-test

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run tests
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/${{ matrix.name }}/devcontainer.json
          imageName: ghcr.io/johnmcfarlane/simple-cpp/${{ matrix.name }}
          imageTag: 2
          runCmd: |
            cmake --build $BUILD_DIR
            ctest --output-on-failure --test-dir $BUILD_DIR

  lint:
    name: lint
    needs: [images]
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run linter
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/lint/devcontainer.json
          imageName: ghcr.io/johnmcfarlane/simple-cpp/base-clang-libcpp
          runCmd: .devcontainer/lint/lint
