---
name: push

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  images:
    name: Build compiler images
    runs-on: ubuntu-latest
    permissions:
      packages: write

    strategy:
      matrix:
        include:
          - name: base-clang
            tag: 4
          - name: base-gcc
            tag: 1

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/${{ matrix.name }}/devcontainer.json
          imageName: ghcr.io/johnmcfarlane/simple-cpp/${{ matrix.name }}
          imageTag: ${{ matrix.tag }}
          runCmd: |
            which conan
            conan --version

  unit-tests:
    name: Test
    needs: [images]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: clang-debug
          - name: clang-release
          - name: clang-test
          - name: clang-tidy
          - name: gcc-debug
          - name: gcc-release
          - name: gcc-test

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run tests
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/${{ matrix.name }}/devcontainer.json
          imageName: ghcr.io/johnmcfarlane/simple-cpp/${{ matrix.name }}
          imageTag: 2
          runCmd: |
            cmake --build $BUILD_DIR
            ctest --output-on-failure --test-dir $BUILD_DIR

  lint:
    name: Lint
    needs: [images]
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run linter
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/lint/devcontainer.json
          imageName: ghcr.io/johnmcfarlane/simple-cpp/base-clang
          runCmd: .devcontainer/lint/lint
