---
name: push

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - name: clang-debug
            imageName: clang
          - name: clang-release
            imageName: clang
          - name: clang-test
            imageName: clang
          - name: clang-tidy
            imageName: clang
          - name: gcc-debug
            imageName: gcc
          - name: gcc-release
            imageName: gcc
          - name: gcc-test
            imageName: gcc

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run tests
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/${{ matrix.name }}/devcontainer.json
          imageName: ghcr.io/johnmcfarlane/${{ matrix.imageName }}
          runCmd: |
            cmake --build $BUILD_DIR
            ctest --output-on-failure --test-dir $BUILD_DIR

  lint:
    name: Run lint tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run linter
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/clang-lint/devcontainer.json
          runCmd: .devcontainer/images/clang/lint
